# Generated by Django 6.1 on 2026-09-05 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp_reward',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Опыт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('failed', 'Провалена')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
    ]
