# Generated by Django 6.1 on 2026-09-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Уровень пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт пользователя'),
        ),
    ]
