# Generated by Django 6.1 on 2026-09-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_level_user_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='xp',
            new_name='xp_amount',
        ),
    ]
